version: 'latest'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: carrental_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: admin123
    ports:
      - 5433:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: