version: 'latest'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5433:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: